### ISSUE TITLE
Error in using audinterface.Feature

### ISSUE THREAD

**Issue by keelezibel** [audeering/w2v2-how-to#13]
```
interface = audinterface.Feature(
    model.outputs["logits"].labels,
    process_func=model,
    process_func_applies_sliding_window=False,
    process_func_args={
        "outputs": "logits",
    },
    sampling_rate=sr,
    resample=True,
    verbose=True,
    win_dur=1.0,
    hop_dur=0.5,
)

AttributeError: type object 'type' has no attribute 'id'.
```
This happened to the latest ver 0.9.0.

**Comment by frankenjoe** [comment]
I'm encountering the same issue in another project and it seems that  `audonnx` is not compatible with the latest version of `audinterface`.

**Comment by hagenw** [comment]
Can be reproduced in #14 :

![image](https://user-images.githubusercontent.com/173624/178934105-cf6a1cea-c147-4916-b603-81ba973aed44.png)

**Comment by hagenw** [comment]
> I'm encountering the same issue in another project and it seems that `audonnx` is not compatible with the latest version of `audinterface`.

It's a little bit unfortunate that now other packages can be incompatible as this could be not only `audonnx` but other stuff as well. So I guess the usage of `signature` seems not to be safe?

**Comment by frankenjoe** [comment]
@keelezibel thanks for reporting the issue, should be fixed now.
