### ISSUE TITLE
Negative values for Arousal

### ISSUE THREAD

**Issue by morvasaati** [audeering/w2v2-how-to#30]
When I run the model, I get some negative values for the arousal element. I thought the arousal, dominance, and valence range is between 0 to 1. Can anyone interpret what is happening or what these negative values mean?

**Comment by hagenw** [comment]
The model is a statistical process and has no fixed boundaries, so it can happen occasionally that it returns values outside of [0, 1]. You could simply add a post-processing and clip the value.

**Comment by morvasaati** [comment]
> The model is a statistical process and has no fixed boundaries, so it can happen occasionally that it returns values outside of [0, 1]. You could simply add a post-processing and clip the value.

**Comment by morvasaati** [comment]
Thanks for your prompt response. What kind of post-processing do you mean? CCan you please explain more about that? And do negative values have meaning in this situation?

**Comment by hagenw** [comment]
For post-processing I simply mean clip the outcome of the model to make sure it is within the interval of [0, 1]:

```python
np.clip(model_result, 0, 1)
```

There is no special meaning if you get back a value <0. It's simply that the model learned to fit a distribution and it can happen that it returns values that are slightly outside of the [0, 1] interval.
