### ISSUE TITLE
Memory Leak during inference

### ISSUE THREAD

**Issue by ligujie123** [audeering/w2v2-how-to#34]
Hi,

I have about more than 100,000 audio files (each audio file is about 1-2 minutes). My goal is to use the API to infer arousal, dominance, and valence from these audio files. I simply use the loop function to feed the audio files to the API one by one, but it seems there is a memory leak problem after 5,000 loops.

The error is like:

[ E : o n n x r u n t i m e : ,  s e q u e n t i a l _ e x e c u t o r . c c : 5 1 4  o n n x r u n t i m e : : E x e c u t e K e r n e l ]  N o n - z e r o  s t a t u s  c o d e  r e t u r n e d  w h i l e  r u n n i n g  S o f t m a x  n o d e .  N a m e : ' S o f t m a x _ 2 4 6 '  S t a t u s  M e s s a g e :  C : \ a \ _ w o r k \ 1 \ s \ o n n x r u n t i m e \ c o r e \ f r a m e w o r k \ b f c _ a r e n a . c c : 3 7 6  o n n x r u n t i m e : : B F C A r e n a : : A l l o c a t e R a w I n t e r n a l  F a i l e d  t o  a l l o c a t e  m e m o r y  f o r  r e q u e s t e d  b u f f e r  o f  s i z e  1 4 3 0 4 1 6 0 0 0 0  

I was wondering is there some way to fix the problem? I am really new to deep learning framework, and look forward to your help. (I am running the code on a CPU machine with 32G ram).

**Comment by Vedaad-Shakib** [comment]
Just to add onto this thread, I'm finetuning this model on my own dataset (model code taken from Huggingface and finetuning using PyTorch-Lightning), and there's a GPU memory leak during finetuning as well. I tried calling `torch.cuda.empty_cache()`, manually garbage collecting, and manually deleting variables that point to GPU memory, but it seems like there is still a leak somewhere. See attached image for a graph of GPU memory allocated over time.

<img width="541" alt="CleanShot 2024-01-11 at 22 51 03@2x" src="https://github.com/audeering/w2v2-how-to/assets/3393996/6c69d741-2419-4b15-9a29-9b9e387c9b98">

**Comment by frankenjoe** [comment]
> I was wondering is there some way to fix the problem?

Do you know if it always crashes with the same file? As a first step we should rule out it is not a specific file in your pool that causes the crash.

**Comment by ligujie123** [comment]
> > I was wondering is there some way to fix the problem?
> 
> Do you know if it always crashes with the same file? As a first step we should rule out it is not a specific file in your pool that causes the crash.

Hi,

No, not the same file. But later I tried the huggingface project through loading the model with transformer package (instead of using the installed audonnx package), and now it seems the for-loop runs smoothly with constantly low memory consumed in the past few hours.

**Comment by frankenjoe** [comment]
Ok, thanks for sharing your experience. So it must be a memory leak with onnxruntime, then. We'll have a look if the issue can be solved on our side.

**Comment by frankenjoe** [comment]
Just to make sure: you instantiated the ONNX model outside the for loop, i.e. you have a single model object that you are re-using inside the loop, right?

**Comment by ligujie123** [comment]
> Just to make sure: you instantiated the ONNX model outside the for loop, i.e. you we re-using the model object inside the loop, right?

Yes, the model was instantiated before (outside) the for loop starts, and only the inference function was used in the loop.

**Comment by frankenjoe** [comment]
Might be related to [this issue](https://github.com/microsoft/onnxruntime/issues/9313)?

Maybe you could try:

```python
options = SessionOptions()
options.enable_cpu_mem_arena = False
options.enable_mem_pattern = False
audonnx.load(..., session_options=options)
```

At least this is something they suggested there, though it seemed not to solve the issue in the end, yet worth a short.

**Comment by ligujie123** [comment]
> Might be related to [this issue](https://github.com/microsoft/onnxruntime/issues/9313)?
> 
> Maybe you could try:
> 
> ```python
> options = SessionOptions()
> options.enable_cpu_mem_arena = False
> options.enable_mem_pattern = False
> audonnx.load(..., session_options=options)
> ```
> 
> At least this is something they suggested there, though it seemed not to solve the issue in the end, yet worth a short.

Thanks! I will take a try after my current for loop finishes (the huggingface one works pretty fine, memory is constantly low after 10,000 times loops)

**Comment by frankenjoe** [comment]
Ok, in case you are still encouraged to look into the ONNX issue, please share your experience. Otherwise have fun with your 100k model predictions :)
